name: karaburun-prod
services:
  app:
    container_name: karaburun-app-prod
    build:
      context: .
      target: production
    # ports:
    #   - "3000:3000"
    env_file:
      - .env.prod
    volumes:
      - ./upload:/app/upload
    command: npm run start
    restart: always
    depends_on:
      - karaburun_db_prod

  karaburun_db_prod:
    container_name: karaburun-db-prod
    image: mariadb:latest
    restart: always
    ports:
      - "3322:3306"
    env_file:
      - .env.prod
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb_data_prod:/var/lib/mysql

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: karaburun-proxy
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx_data:/data
      - ./nginx_letsencrypt:/etc/letsencrypt
volumes:
  mariadb_data_prod: