services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - karaburun_db

  karaburun_db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root123
      - MARIADB_DATABASE=karaburun
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: